# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/sony/extra-yodo/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/extra-yodo/common

PRODUCT_COPY_FILES += \
    vendor/sony/extra-yodo/common/proprietary/product/app/SomcMediaExtensionProviderStarter/lib/arm64/libmepstarterjni.so:$(TARGET_COPY_OUT_PRODUCT)/app/SomcMediaExtensionProviderStarter/lib/arm64/libmepstarterjni.so \
    vendor/sony/extra-yodo/common/proprietary/product/etc/default-permissions/pre_grant_permissions_oem.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/default-permissions/pre_grant_permissions_oem.xml \
    vendor/sony/extra-yodo/common/proprietary/product/etc/permissions/com.google.protobuf-2.3.0.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.protobuf-2.3.0.xml \
    vendor/sony/extra-yodo/common/proprietary/product/etc/permissions/com.sonyericsson.music.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonyericsson.music.xml \
    vendor/sony/extra-yodo/common/proprietary/product/etc/permissions/com.sonymobile.extmonitorapp.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.extmonitorapp.xml \
    vendor/sony/extra-yodo/common/proprietary/product/etc/permissions/com.sonymobile.home.resourceprovider.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.home.resourceprovider.xml \
    vendor/sony/extra-yodo/common/proprietary/product/etc/permissions/com.sonymobile.moviecreator.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.moviecreator.xml \
    vendor/sony/extra-yodo/common/proprietary/product/etc/permissions/jp.co.sony.mc.usbextoutaudio.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/jp.co.sony.mc.usbextoutaudio.xml \
    vendor/sony/extra-yodo/common/proprietary/product/etc/sysconfig/extmonitorapp-initial-package-stopped-states.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/extmonitorapp-initial-package-stopped-states.xml \
    vendor/sony/extra-yodo/common/proprietary/system_ext/etc/permissions/com.sonymobile.colorgamut.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.sonymobile.colorgamut.xml

PRODUCT_PACKAGES += \
    SomcDualshockManager \
    SomcMediaExtensionProviderStarter \
    ExtMonitorApp \
    SomcMediaExtensionProvider-Yodo \
    UsbExtOutAudio \
    SomcColorGamut \
    com.google.protobuf-2.3.0-dummy \
    com.sonymobile.home.resourceprovider
